#Lance les tests par mutation pour chaque tag
name: tag PiTest

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      
      
      with:
        java-version: 1.17
    - name: Launch piTest in Player
      run: |
        cd Player
        mvn test -Pmutation
